[package]
name = "server_two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.9.0
image = "0.24.0"  # or the version you want
tokio = { version = "1", features = ["full"] }
